/*!

JSZipUtils - A collection of cross-browser utilities to go along with JSZip.
<http://stuk.github.io/jszip-utils>

(c) 2014 Stuart Knightley, David Duponchel
Dual licenced under the MIT license or GPLv3. See https://raw.github.com/Stuk/jszip-utils/master/LICENSE.markdown.

*/
!function(a){"object"==typeof exports?module.exports=a():"function"==typeof define&&define.amd?define(a):"undefined"!=typeof window?window.JSZipUtils=a():"undefined"!=typeof global?global.JSZipUtils=a():"undefined"!=typeof self&&(self.JSZipUtils=a())}(function(){return function a(b,c,d){function e(g,h){if(!c[g]){if(!b[g]){var i="function"==typeof require&&require;if(!h&&i)return i(g,!0);if(f)return f(g,!0);throw new Error("Cannot find module '"+g+"'")}var j=c[g]={exports:{}};b[g][0].call(j.exports,function(a){var c=b[g][1][a];return e(c?c:a)},j,j.exports,a,b,c,d)}return c[g].exports}for(var f="function"==typeof require&&require,g=0;g<d.length;g++)e(d[g]);return e}({1:[function(a,b){"use strict";function c(){try{return new window.XMLHttpRequest}catch(a){}}function d(){try{return new window.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}}var e={};e._getBinaryFromXHR=function(a){return a.response||a.responseText};var f=window.ActiveXObject?function(){return c()||d()}:c;e.getBinaryContent=function(a,b){try{var c=f();c.open("GET",a,!0),"responseType"in c&&(c.responseType="arraybuffer"),c.overrideMimeType&&c.overrideMimeType("text/plain; charset=x-user-defined"),c.onreadystatechange=function(){var d,f;if(4===c.readyState)if(200===c.status||0===c.status){d=null,f=null;try{d=e._getBinaryFromXHR(c)}catch(g){f=new Error(g)}b(f,d)}else b(new Error("Ajax error for "+a+" : "+this.status+" "+this.statusText),null)},c.send()}catch(d){b(new Error(d),null)}},b.exports=e},{}]},{},[1])(1)});
var _global="object"===typeof window&&window.window===window?window:"object"===typeof self&&self.self===self?self:"object"===typeof global&&global.global===global?global:this;
function bom(a,b){"undefined"===typeof b?b={autoBom:!1}:"object"!==typeof b&&(console.warn("Depricated: Expected third argument to be a object"),b={autoBom:!b});return b.autoBom&&/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(a.type)?new Blob([String.fromCharCode(65279),a],{type:a.type}):a}
function download(a,b,e){var c=new XMLHttpRequest;c.open("GET",a);c.responseType="blob";c.onload=function(){saveAs(c.response,b,e)};c.onerror=function(){console.error("could not download file")};c.send()}function corsEnabled(a){var b=new XMLHttpRequest;b.open("HEAD",a,!1);b.send();return 200<=b.status&&299>=b.status}
function click(a){try{a.dispatchEvent(new MouseEvent("click"))}catch(e){var b=document.createEvent("MouseEvents");b.initMouseEvent("click",!0,!0,window,0,0,0,80,20,!1,!1,!1,!1,0,null);a.dispatchEvent(b)}}
var saveAs=_global.saveAs||"object"!==typeof window||window!==_global?function(){}:"download"in HTMLAnchorElement.prototype?function(a,b,e){var c=_global.URL||_global.webkitURL,d=document.createElement("a");b=b||a.name||"download";d.download=b;d.rel="noopener";"string"===typeof a?(d.href=a,d.origin!==location.origin?corsEnabled(d.href)?download(a,b,e):click(d,d.target="_blank"):click(d)):(d.href=c.createObjectURL(a),setTimeout(function(){c.revokeObjectURL(d.href)},4E4),setTimeout(function(){click(d)},
0))}:"msSaveOrOpenBlob"in navigator?function(a,b,e){b=b||a.name||"download";if("string"===typeof a)if(corsEnabled(a))download(a,b,e);else{var c=document.createElement("a");c.href=a;c.target="_blank";setTimeout(function(){click(c)})}else navigator.msSaveOrOpenBlob(bom(a,e),b)}:function(a,b,e,c){if(c=c||open("","_blank"))c.document.title=c.document.body.innerText="downloading...";if("string"===typeof a)return download(a,b,e);b="application/octet-stream"===a.type;e=/constructor/i.test(_global.HTMLElement)||
_global.safari;var d=/CriOS\/[\d]+/.test(navigator.userAgent);if((d||b&&e)&&"object"===typeof FileReader){var f=new FileReader;f.onloadend=function(){var a=f.result;a=d?a:a.replace(/^data:[^;]*;/,"data:attachment/file;");c?c.location.href=a:location=a;c=null};f.readAsDataURL(a)}else{var h=_global.URL||_global.webkitURL,g=h.createObjectURL(a);c?c.location=g:location.href=g;c=null;setTimeout(function(){h.revokeObjectURL(g)},4E4)}};_global.saveAs=saveAs.saveAs=saveAs;
"undefined"!==typeof module&&(module.exports=saveAs);